opencti:
  url: ${OPENCTI_URL}
  token: ${OPENCTI_TOKEN}

connector:
  id: ${CONNECTOR_ID}
  type: "EXTERNAL_IMPORT"
  name: "OpenCTI NetManageIT Connector"
  scope: "opencti-netmanageit"
  log_level: "info"
  run_and_terminate: "False"
  send_to_queue: "True"
  send_to_directory: "False"

opencti_netmanageit:
  url: ${OPENCTI_NETMANAGEIT_URL}
  token: ${OPENCTI_NETMANAGEIT_TOKEN}

# Connector behavior flags
connector_flags:
  process_observables: true
  process_indicators: true

github:
  api_base_url: ${GITHUB_API_BASE_URL}
  github_token: ${GITHUB_TOKEN}
